CREATE TABLE CLIENT (
    CL_ID INT AUTO_INCREMENT PRIMARY KEY,
    CL_NAME VARCHAR(255) NOT NULL,
    CL_SECOND_NAME VARCHAR(255) NOT NULL,
    CL_BIRTHDAY DATETIME NOT NULL,
    CL_NATIONNALITE VARCHAR(100) NOT NULL,
    CL_COUNTRY_STAY VARCHAR(100) NOT NULL,
    CL_ADDRESSE VARCHAR(255) NOT NULL,
    CL_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CL_PROFESSION VARCHAR(100) NOT NULL,
    CL_PROVENANCE VARCHAR(100),
    CL_DESTINATION VARCHAR(100),
    CL_PARENT_NAME VARCHAR(255),
    CL_IDENTITY_PIECE VARCHAR(100) UNIQUE NOT NULL,
    CL_DELIVRANCE_DATE DATE NOT NULL,
    CL_TRANSPORT_MODE VARCHAR(50),
    CL_IMMATRICULATION VARCHAR(100),
    CL_CONTACT VARCHAR(20),
    CL_PASSWORD VARCHAR(255) DEFAULT "0000"
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

